// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteQuote struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type NewQuote struct {
	Quote  string `json:"quote"`
	Author string `json:"author"`
}

type Quote struct {
	ID     string `json:"id"`
	Quote  string `json:"quote"`
	Author string `json:"author"`
}
